
title: "Keith Roberts"
description: "Welcome to my personal academic website. My name is Keith Roberts and I am a PhD Candidate in Economics and a Researcher in Behavioral and Neuroeconomics. Here you will find all projects and my CV."

url: "https://keithrobert117.github.io"
baseurl: ""

# Theme settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache

# Author info (for sidebar/profile)
author:
  name: "Keith Roberts"
  avatar: "/assets/images/profile.jpg"
  bio: "PhD Candidate – McMaster University"
  location: "Hamilton, Canada"
  email: "roberk40@mcmaster.ca"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "roberk40@mcmaster.ca"
    - #label: "Google Scholar"
      #icon: "ai ai-google-scholar"
      #url: "https://scholar.google.com/..."
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/KeithRoberts117"



# Defaults for pages
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
