theme: jekyll-theme-minimal
title: Keith Roberts' Homepage
description: Welcome to my personal academic website. My name is Keith Roberts and I am a PhD Student in Economics and a Researcher in Behavioral and Neuroeconomics. Here you will find all projects and my CV.
