theme: jekyll-theme-minimal
title: "Keith Roberts"
description: "Welcome to my personal academic website. My name is Keith Roberts and I am a PhD Candidate in Economics and a Researcher in Behavioral and Neuroeconomics. Here you will find all projects and my CV."
