
title: "Keith Roberts"
description: "Welcome to my personal academic website. My name is Keith Roberts and I am a PhD Candidate in Economics and a Researcher in Behavioral and Neuroeconomics. Here you will find all projects and my CV."

url: "https://keithrobert117.github.io"
baseurl: ""

# Theme settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache

# Author info (for sidebar/profile)
author:
  name: "Keith Roberts"
# avatar: ""
  bio: "PhD Candidate - McMaster Univesity"
  location: "Hamilton, Canada"
  email: "roberk40@mcmaster.ca"

# Defaults for pages
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
